config/routes.rb
Rails.application.routes.draw do
  devise_for :members
  root 'users#index'  
  resources :users, only: [:index, :show], format: 'json' do
    resources :posts, only: [:index, :show, :new, :create, :destroy], format: 'json' do
      resources :comments, only: [:index, :create, :destroy], format: 'json'
      resources :likes, only: [:create]
    end
  end
end

app/models/member.rb
class Member < ActiveRecord::Base
  has_one :user
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  ROLES = %w[admin user public].freeze
  ROLES.each do |role_name|
    define_method "#{role_name}?" do
      role == role_name
    end
  end
end

app/controllers/members/sessions_controller.rb
class Members::SessionsController < Devise::SessionsController
  def create
    member = Member.find_by(email: sign_in_params[:email])
    if member&.valid_password?(sign_in_params[:password])
      secret = Rails.application.secrets.secret_key_base
      payload = { sub: member.id, exp: 24.hours.from_now.to_i }
      token = JWT.encode({ sub: member.id, exp: 24.hours.from_now.to_i }, Rails.application.secrets.secret_key_base)
      render json: { jwt: token }, status: :created
    else
      head :unauthorized
    end
  end

  private

  def sign_in_params
    params.require(:member).permit(:email, :password)
  end
end

app/views/layouts/member/_session_manager.html.erb
<% if current_member %>
  <li class="nav-item">
    <a class="nav-link active" aria-current="page" href="#">Home</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="#">Link</a>
  </li>
  <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
      Dropdown
    </a>
    <ul class="dropdown-menu">
      <li><a class="dropdown-item" href="#">Action</a></li>
      <li><a class="dropdown-item" href="#">Another action</a></li>
      <li>
        <hr class="dropdown-divider">
      </li>

      <li>
        <%= button_to "Logout" , destroy_member_session_path, method: :delete, class:"dropdown-item"%>
      </li>
    </ul>
  </li>
  <%else%>
    <li class="nav-item">
      <%= link_to "Sign Up" , new_member_registration_path%>
    </li>
    <li class="nav-item">
      <%= link_to "Log In" , new_member_session_path%>
    </li>
  <%end%>