config/routes.rb
Rails.application.routes.draw do
  devise_for :members
  root 'users#index'  
  resources :users, only: [:index, :show], format: 'json' do
    resources :posts, only: [:index, :show, :new, :create, :destroy], format: 'json' do
      resources :comments, only: [:index, :create, :destroy], format: 'json'
      resources :likes, only: [:create]
    end
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user, class_name: 'User'
  has_many :comments, class_name: 'Comment', foreign_key: 'post_id'
  has_many :likes, class_name: 'Like', foreign_key: 'post_id'

  validates :title, presence: true, length: { in: 1..250 }
  validates :text, presence: true, length: { in: 1..500 }
  validates :comments_counter, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  after_create :update_posts_counter

  def update_posts_counter
    user.posts_counter = user.posts.count
    user.save
  end

  def recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  def self.user_post(user_id, post_id)
    Post.where(user_id:, id: post_id).includes(:comments, :user).first
  end

  def self.user_comments(user_id, post_id)
    Comment.where(user_id:, post_id:)
  end

  def self.user_posts(user_id)
    Post.includes(:comments).where(user_id:)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[show destroy]
  before_action :authorize_delete, only: [:destroy]

  def index
    @posts = Post.user_posts(params[:user_id]).paginate(page: params[:page], per_page: 10)
    respond_to do |format|
      format.html
      format.json { render json: @posts }
    end
  end

  def show
    @post = Post.user_post(params[:user_id], params[:id])
  end

  def new
    user = User.get_user(current_member.id)
    @post = Post.new
    @post.user = user
    @post.comments_counter = 0
    @post.likes_counter = 0
  end

  def add_comment; end

  def create
    @user = User.find(params[:user_id])
    @post = @user.posts.build(post_params)
    @post.comments_counter = 0
    @post.likes_counter = 0
    if @post.valid?
      @post.save
      flash[:notice] = 'Post created successfully!'
      redirect_to new_user_post_path(@user, @post)
    else
      flash[:error] = @post.errors.full_messages.join(', ')
      render :new
    end
  end

  def destroy
    @post.destroy
    redirect_to user_post_path(user_id: @post.user_id, id: @post.id), notice: 'Post was successfully deleted.'
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def authorize_delete
    return if can? :delete, @post

    redirect_to user_post_path(user_id: @post.user_id, id: @post.id), notice: 'You are not authorized to delete this post.'
  end

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/index.html.erb
<% require 'will_paginate/view_helpers/action_view' %>
<div class="user-wrapper">
  <div class="user-container">
    <div class="user-list">
      <% if @posts.first.try(:user).present? %>
        <span class="photo">
          <%= image_tag(@posts.first.user.photo, size: "100x100") %>
        </span>
        <span class="user-info">
          <span>
            <%= link_to @posts.first.user.name, user_post_path(user_id: @posts.first.user.id, id: @posts.first.id) %>
          </span>
          <span>
            number of posts: <%= @posts.first.user.posts_counter ? @posts.first.user.posts_counter : 0 %>
          </span>
        </span>
      <% end %>
    </div>
    <%= link_to 'New Post', new_user_post_path %>
    <div class="pagination">
      <%= will_paginate @posts, class: "pagination", :previous_label => 'Previous', :next_label => 'Next', :inner_window => 2, :outer_window => 0 %>
    </div>
    <% if @posts.first.try(:user).present? %>
      <%=@posts.count%> posts written by <%=@posts.first.user.name%>
    <% end %>
    <%@posts.each do |post|%>
      <div class="post-list">
        <span class="post-text">
          <span>
            <%= link_to "Post #: #{post.id}", url_for(controller: 'posts', action: 'show', id: post.id) %>
          </span>
          <span>
            <%= post.text %>
          </span>
          <span>
            <% if can? :delete, post %>
      <%= button_to 'Delete',  user_post_path(user_id:post.user_id, id: post.id), method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
          </span>
          <span>comments: <%= post.comments.count %>&nbsp; likes: <%= post.likes.count %></span>
        </span>
        <ul class="comment-text">
          <%post.recent_comments.each do |comment|%>
            <li>
              <%= post.user.try(:name) %>:<%=comment.text%>
            </li>
          <%end%>
        </ul>
      </div>
    <%end%>
    <%= will_paginate @posts, class: "pagination", :previous_label => 'Previous', :next_label => 'Next', :inner_window => 2, :outer_window => 0 %>
  </div>
</div>

app/views/posts/new.html.erb
<div>
    <%= form_with(model: [@user, @post], local: true, url: user_posts_path(user_id: @post.user_id)) do |form| %>
  <%= form.hidden_field :user_id, value: @post.user_id %>
  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= form.label :text %>
    <%= form.text_area :text, class: 'form-control' %>
  </div>
  <%= form.submit "Create Post", class: "btn btn-primary" %>
<% end %>
</div>
<div>
    <% if flash[:error] %>
    <div class="alert alert-danger">
      <%= flash[:error] %>
    </div>
  <% end %>
  <% if flash[:notice] %>
    <div class="alert alert-success">
      <%= flash[:notice] %>
    </div>
  <% end %>
</div>

app/views/posts/show.html.erb
<div class="user-wrapper">
  <div class="user-container">
    <h1><%=@post.title%></h1>
    <div class="user-list">
      <span class="photo">
        <%= image_tag(@post.user.photo, size: "100x100" ) %>
      </span>
      <span class="user-info">
        <span>
          <%= link_to @post.user.name, user_path(user_id: @post.user.id, format:
          :html) %>
        </span>
        <span>
          number of posts: <%= @post.user.posts_counter ?
          @post.user.posts_counter : 0 %>
        </span>
      </span>
    </div>
    <ul class="posts">
      <li>
        <span>
          <%= link_to "Post #: #{@post.id}" , user_post_path(user_id:
          @post.user.id, post_id: @post.id) %> by <%=@post.user.name%>
        </span>
        <span> <%= @post.text %> </span>
        <span
          >comments: <%= @post.comments.count %>&nbsp;<%= button_to "likes:
          #{@post.likes.count}", user_post_likes_path(user_id: @post.user.id,
          post_id: @post.id), method: :post %>
        </span>
      </li>
    </ul>

    <%= form_with(model: [@post, @post.comments.build], url:
    user_post_comments_path(user_id: @post.user_id, post_id: @post.id), class:
    "form-horizontal" ) do |form| %>
    <div class="form-group">
      <%= form.label :text, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= form.text_area :text, class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= form.submit "Add Comment" , class: "btn btn-primary" %>
      </div>
    </div>
    <% end %>

    <ul class="comments">
      
      <% if @post.comments.count > 0%> 
      <% @post.comments.each do |comment| %>
      <li><%= @post.user.name %> : <%= comment.text %></li>
      <% if comment.id?%>
      <%= button_to 'Delete', user_post_comment_path(user_id:
      comment.post.user_id, post_id: comment.post_id, id: comment.id), method:
      :delete, data: { confirm: 'Are you sure?' } %> 
      <%end%>
      <% end %> 
      <% end %>
    </ul>
  </div>
</div>